--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Faizx511x/GameUI-Beta
build-by-default: true
branches:
- main
projects:
  GameUI-Beta:
    path: ""
     lint:
      phpstan: false
    libs:
      - src: jojoe77777/FormAPI/FormAPI
        version: ^1.1.2
...
