name: GameUI
main: GameUI\GameUI
api: 4.0.0
version: 1.0
author: ["FaizDev", "ItsToxicGG"]

commands:
  games:
    description: GamesUi Command
    usage: /games
    permission: games.cmd

permissions:
  games.cmd:
    default: true
    description: "Allows to open the Gamres UI"
